[package]
name = "regolith-powerd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-channel = "2.1.1"
gio = "0.18.4"
glib = "0.18.5"
gsettings-macro = "0.1.20"
swayipc = "3.0.1"
zbus = "4.2.2"
